import {loginMarkup,businessMarkup} from './qa-modals.js?v=20260915-v4';
import {readUsers,requestAccess,submitBusiness,subscribeUsers,resetDemo,SESSION_KEY} from './store.js';
const $=s=>document.querySelector(s);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const image=name=>`assets/${name}`;
const views={home:['首页 · 创作入口','home',1,'入口名称与四项工具副标题'],novels:['小说IP库','library',4,'内容尾部增加登录入口，登录后隐藏'],scripts:['剧本库','library',4,'内容尾部增加登录入口，登录后隐藏']};
const quick=[['小说创作','从题材构思到章节续写，辅助完成小说创作','quick-novel.png'],['AI剧本','输入故事设定，生成大纲与分集剧本','quick-script.png'],['无限画布','自由连接创作节点，组合素材与生成流程','quick-canvas.png'],['快速创作','整合角色、分镜与视频生成，完成 AI 漫剧制作','quick-drama.png']];
const novels=[
 ['孤舟不系','溪午',"发小又一次拿着我的手机发了“婚礼取消”的消息后，我邦邦两拳。别拿婚礼开玩笑，我女朋友会不高兴。”“她是不小心才把婚戒弄丢了，罪不至死，我都已经找回来了。”",'现代言情','1.01万字'],
 ['他到死才懂，我是他唯一的解药','招财猫很招财',"谢衡单膝跪地，给了我一场轰动全城的求婚。此时系统显示：目标谢衡，当前好感度90%。【恭喜宿主，目标好感度还差10%，完成即可彻底解除死亡危机。】",'现代言情','9220字'],
 ['冲掉心中爱的馀味再活一遍','竹官',"导游说在塔尔寺捡到落叶的人会被幸运眷顾。我在树下等了40分钟。闺蜜睡醒午觉从车上走下来时，男友打开了手里的遮阳伞。“夏梦，你还要站多久，太晒了。”",'现代言情','8234字'],
 ['人见不相逢','大捷',"结婚前一天，当年欺负过我的地痞混子发了条勒索短信。“姜眠，听说你要结婚了，为了你，我可是整整坐了三年牢。”面对着曾经欺负过我的人渣，我气得想再次报警。",'现代言情','9240字'],
 ['山河不斜，我自归平','没感情的毒妇',"临睡前，我刷到了一条距离我不足0.1km的帖子。【老公中了1000万，怎么说服他净身出户成全我和竹马？】我猜想发帖人肯定是附近的女邻居，抱着近距离吃瓜的心态，果断点了进去。",'现代言情','1.08万字'],
 ['恨一场桂花雨落','吉吉',"最恶毒那年，我以沈邺妹妹的性命为要挟。逼爱干净的他咽下满满一盒土灰。然后告诉他。其实他吃的是他妹妹的骨灰。所以多年后，沈邺带兵杀入大盛皇都后的第一件事，就是重金悬赏捉拿我。",'古代言情','9949字']
].map((r,i)=>({id:`novel-${i}`,title:r[0],author:r[1],desc:r[2],genre:r[3],words:r[4],cover:`qa-novel-${i+1}.jpg`,channel:'女频',length:'短篇'}));
const scripts=['诊室全程录音后，她慌了','满级福星驾到','重生之我不是软柿子','二十年终得昭雪','我花三万请月嫂，她全家搬进来','妈妈捡了四个爹','保洁阿姨让我嫁给她弟弟','八零甜宠：谁动了我夫人','他救白月光，我嫁摄政王','我的陪嫁房，成了小叔子婚房'].map((title,i)=>({id:`cn-script-${i}`,title:`《${title}》`,cover:`qa-script-${i+1}.jpg`,genre:['幻想脑洞','幻想脑洞','年代现实','悬疑惊悚','幻想脑洞','幻想脑洞','幻想脑洞','年代现实','古代言情','现代言情'][i],channel:i===3?'男频':'女频'}));
const overseasScripts=['Oops!My Billionaire Baby Daddy','My Fucking Marriage Goes to the Hell','Mr. Sheriff, Let’s Get Divorced','Left For Dead','DragonMom: My Identity Exposed After Birth'].map((title,i)=>({id:`overseas-script-${i}`,title,cover:`overseas-script-${i+1}.jpg`,genre:'现代言情',channel:'女频'}));
const featureData={novels:[['小说投稿入库','提交原创小说与版权资料，完成内容审核与IP入库。','blue','▤'],['AI小说创作','输入创意与题材，智能完成大纲及章节创作。','purple','✦'],['商务合作','连接IP合作、漫剧制作与全域发行资源。','orange','◇']],scripts:[['小说智能改编','提炼情节与角色，快速生成漫剧剧本。','blue','▤'],['AI原创剧本','输入创意，智能生成大纲与分集剧本。','teal','▧'],['剧本智能评估','智能分析结构、角色与市场潜力。','purple','▥']]};
const state={view:'home',region:'国内版',session:null,query:'',genre:'',channel:'',length:'',failNext:false};
try{state.session=JSON.parse(localStorage.getItem(SESSION_KEY)||'null');}catch{state.session=null;}
let modalSource='顶部登录',modalPhone='',codePhone='',codeExpires=0,codeTimer=null,loginBusy=false;
let focusOnClose=null;
function currentUser(){return state.session?.region===state.region ? readUsers().find(x=>x.phone===state.session.phone&&x.status==='approved') : null;}
function syncPrd(section=views[state.view][1]){if(window.parent!==window)window.parent.postMessage({type:'wanxiang-prd-section',section},location.origin);}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function params(){const p=new URLSearchParams(location.search);state.region=p.get('edition')==='overseas'?'海外版':'国内版';state.view=views[location.hash.slice(1)]?location.hash.slice(1):'home';}
function navigate(view,{region=state.region}={}){const u=new URL(location.href);u.searchParams.set('edition',region==='海外版'?'overseas':'domestic');u.searchParams.delete('script');u.hash=view;history.pushState(null,'',u);state.query='';state.genre='';state.channel='';state.length='';params();render();window.scrollTo({top:0,behavior:'instant'});}
function renderNav(){const logged=currentUser();$('#siteNav').innerHTML=`<a href="#home" class="logo" data-route="home" aria-label="容量万相首页"><img src="${image('logo.png')}" alt="容量·万相"></a><nav class="site-links" aria-label="官网导航">${[['home','首页'],['novels','小说IP库'],['scripts','剧本库']].map(([v,t])=>`<a href="#${v}" data-route="${v}" class="${state.view===v?'active':''}">${t}${v==='novels'?'<span class="prd-pin" data-prd-number="4" title="PRD 4 · 内容库查看更多" aria-hidden="true">4</span>':''}</a>`).join('')}<button class="out-scope" data-unrelated="资产库">资产库</button><button class="out-scope" data-unrelated="Agent工具">Agent工具</button><button class="out-scope" data-unrelated="生态创新中心">生态创新中心</button><button class="studio" data-tool="AI漫剧制作"><span>漫剧制作</span><em><span>HOT</span></em></button></nav><div class="nav-actions"><button id="switchEdition">${state.region==='国内版'?'前往海外版':'返回国内版'} ›<span class="prd-pin" data-prd-number="2" title="PRD 2 · 海外入口文案" aria-hidden="true">2</span></button><button id="navLogin" class="${logged?'account':''}">${logged?esc(logged.phone.slice(0,3)+'****'+logged.phone.slice(-4)):'登录'}<span class="prd-pin" data-prd-number="3" title="PRD 3 · 审核制登录" aria-hidden="true">3</span></button></div>`;
  const v=views[state.view];$('#contextLine').innerHTML=`<span class="edition">${state.region} · 简体中文</span><span class="change-note"><span class="number">${v[2]}</span>${v[3]} <a href="prd.html#${v[1]}" target="_blank">查看说明 ↗</a></span>`;$('#prdLink').href=`prd.html#${v[1]}`;
}
function empty(title,desc,reset=false){return `<div class="empty-state"><span class="empty-icon">▧</span><h2>${title}</h2><p>${desc}</p>${reset?'<button data-reset-search style="margin-top:20px">清空筛选</button>':''}</div>`;}
function homePage(){return `<section><div class="section-heading"><h1 class="prd-anchor">开启新的AI故事灵感<span class="prd-pin" data-prd-number="1" title="PRD 1 · 首页创作入口文案" aria-hidden="true">1</span></h1><p>无论是创作漫剧、孵化IP，还是商务合作，从这里开始</p></div><div class="quick-grid">${quick.map((r,i)=>`<button class="quick-card ${i===3?'featured':''}" data-tool="${r[0]}" style="--preview-width:108px"><span class="qa-quick-bg"></span>${i===3?'<span class="qa-quick-beam"></span>':''}<span class="qa-quick-content"><span class="qa-quick-top"><img class="qa-quick-icon" src="assets/qa-icon-${i+1}.svg" alt=""><h2>${r[0]}</h2></span><p>${r[1]}</p></span><span class="qa-quick-preview"><img src="${image(r[2])}" alt=""></span>${i>=2?`<span class="new">${i===2?'NEW':'推荐'}</span>`:''}</button>`).join('')}</div></section>`;}
function features(kind){return `<section class="feature-grid" data-kind="${kind}" aria-label="${kind==='novels'?'小说':'剧本'}能力入口">${featureData[kind].map(r=>`<button class="feature-card ${r[2]}" data-tool="${r[0]}"><span class="feature-content"><h3>${r[0]}</h3><p>${r[1]}</p><b>立即体验</b></span></button>`).join('')}</section>`;}
function selectFilter(name,title,options){return `<div class="filter-select"><button type="button" class="filter-select__trigger" data-filter-toggle="${name}" aria-label="${title}" aria-expanded="false"><span class="filter-select__label">${state[name]||title}</span><svg class="filter-select__arrow" width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M4 6L8 10L12 6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></button><div class="filter-select__panel" id="filter-${name}" hidden>${['',...options].map(o=>`<button class="filter-select__option ${state[name]===o?'is-active':''}" data-filter-name="${name}" data-filter-value="${o}">${o||title}</button>`).join('')}</div></div>`;}
function searchBox(){return `<label class="search-box"><span aria-hidden="true"><img src="assets/qa-search-icon.svg" width="20" height="20" alt=""></span><input id="search" aria-label="搜索内容" placeholder="搜索" value="${esc(state.query)}"></label>`;}
function gate(){return currentUser()?'':`<section class="more-gate" id="moreGate"><div class="mini-label"><span class="number">4</span>更多精彩内容</div><button class="primary" id="moreButton"><span class="prd-pin" data-prd-number="4" title="PRD 4 · 内容库查看更多" aria-hidden="true">4</span>查看更多 <span aria-hidden="true">→</span></button><p>登录后继续浏览 · 登录权限需经商务审核开通</p></section>`;}
function libraryPage(kind){const isNovel=kind==='novels';const entries=isNovel?(state.region==='国内版'?novels:[]):(state.region==='国内版'?scripts:overseasScripts);const genres=[...new Set(entries.map(r=>r.genre))];return `${features(kind)}${state.region==='海外版'?`<div class="inline-notice">${isNovel?'海外小说内容独立维护，业务暂定提供 18 篇；当前展示待补充状态。':'海外剧本使用独立内容资源，页面默认中文。'}</div>`:''}<div class="library-filters"><div class="selects">${isNovel?selectFilter('length','全部篇幅',['短篇','中篇']):''}${selectFilter('channel','全部频道',['女频','男频'])}${selectFilter('genre','全部分类',genres)}</div>${searchBox()}</div><div id="libraryResults" class="${isNovel?'novel-grid':'poster-grid'}"></div><div id="gateSlot">${gate()}</div><div class="result-info" id="resultInfo"></div>`;}
function renderLibraryResults(){const isNovel=state.view==='novels';const all=isNovel?(state.region==='国内版'?novels:[]):(state.region==='国内版'?scripts:overseasScripts);const matched=all.filter(x=>(!state.query||(x.title+x.author+x.genre).toLowerCase().includes(state.query.toLowerCase()))&&(!state.genre||x.genre===state.genre)&&(!state.channel||x.channel===state.channel)&&(!state.length||x.length===state.length));$('#libraryResults').innerHTML=matched.length?matched.map(x=>isNovel?`<button class="novel-card" data-novel="${x.id}"><span class="novel-cover"><img src="${image(x.cover)}" alt="${esc(x.title)}"></span><span class="novel-copy"><h3>${esc(x.title)}</h3><span class="metadata"><span class="tag">${x.genre}</span><span>短篇</span><span>${x.words}</span></span><p>${esc(x.desc)}</p><span class="author">作者：${esc(x.author)}</span></span></button>`:`<button class="poster-card" data-script="${x.id}"><span class="cover" style="display:block"><img src="${image(x.cover)}" alt="${esc(x.title)}"><span class="genre">${x.genre}</span></span><h3>${esc(x.title)}</h3></button>`).join(''):empty(all.length?'暂无匹配内容':'内容筹备中',all.length?'试试其他关键词，或调整筛选条件。':'海外小说将由业务统一提供，敬请期待。',!!all.length);$('#resultInfo').textContent=`${matched.length?`当前展示 ${matched.length} 部内容`:'暂无内容'}${currentUser()?' · 已登录':''}`;}
function render(){renderNav();$('#page').innerHTML=state.view==='home'?homePage():libraryPage(state.view);if(['novels','scripts'].includes(state.view))renderLibraryResults();document.title=views[state.view][0]+' · '+state.region+'｜容量万相需求 Demo';syncPrd();}
function modalShell(content,small=false){focusOnClose=focusOnClose||document.activeElement;$('#modalLayer').innerHTML=`<section class="modal-dialog ${small?'modal-small':''}" role="dialog" aria-modal="true" aria-labelledby="modalTitle"><button class="modal-close" aria-label="关闭弹窗" data-close>×</button>${content}</section>`;$('#modalLayer').hidden=false;$('#siteShell').inert=true;$('.reviewbar').inert=true;$('#demoTools').inert=true;$('.floating-actions').inert=true;document.body.style.overflow='hidden';requestAnimationFrame(()=>$('#modalLayer').querySelector('input,button:not(.modal-close),button')?.focus({preventScroll:true}));syncPrd($('#loginForm')||$('#permissionPrimary')||$('#backPermission')?'login':views[state.view][1]);}
function closeModal(){if(loginBusy)return;clearInterval(codeTimer);$('#modalLayer').hidden=true;$('#modalLayer').innerHTML='';$('#siteShell').inert=false;$('.reviewbar').inert=false;$('#demoTools').inert=false;$('.floating-actions').inert=false;document.body.style.overflow='';focusOnClose?.isConnected&&focusOnClose.focus({preventScroll:true});focusOnClose=null;syncPrd();}
function rawModal(content){focusOnClose=focusOnClose||document.activeElement;$('#modalLayer').innerHTML=content;$('#modalLayer').hidden=false;$('#siteShell').inert=true;$('.reviewbar').inert=true;$('#demoTools').inert=true;$('.floating-actions').inert=true;document.body.style.overflow='hidden';requestAnimationFrame(()=>$('#modalLayer').querySelector('input:not([type="hidden"])')?.focus({preventScroll:true}));syncPrd('login');}
function openLogin(source='顶部登录',phone='',preset=false){modalSource=source;modalPhone=phone;clearInterval(codeTimer);codePhone=preset?phone:'';codeExpires=preset?Date.now()+300000:0;rawModal(loginMarkup(phone,preset));}
function business(){clearInterval(codeTimer);rawModal(businessMarkup(modalPhone));}
function businessData(){return {name:$('#business-name').value.trim(),company:$('#business-company').value.trim(),contact:$('#business-contact').value.trim(),role:$('#business-role').value,direction:JSON.parse($('#business-direction').value||'[]'),needs:$('#business-needs').value.trim()};}
function updateBusiness(){const d=businessData();$('#business-count').textContent=`${$('#business-needs').value.length} / 500`;const valid=d.name&&d.company&&/^1[3-9]\d{9}$/.test(d.contact)&&d.direction.length&&d.needs&&$('#business-agreement').checked;$('#business-submit').disabled=!valid;$('#business-submit').classList.toggle('is-disabled',!valid);}
function toggleBusiness(kind){const trigger=$('#business-'+kind+'-trigger'),panel=$('#business-'+kind+'-menu');const open=panel.hidden;document.querySelectorAll('#businessForm .select-dropdown').forEach(x=>x.hidden=true);document.querySelectorAll('[data-biz-toggle]').forEach(x=>{x.setAttribute('aria-expanded','false');x.closest('.form-select')?.classList.remove('is-open');});panel.hidden=!open;trigger.setAttribute('aria-expanded',String(open));trigger.closest('.form-select')?.classList.toggle('is-open',open);}
function pickBusiness(kind,value){const input=$('#business-'+kind),trigger=$('#business-'+kind+'-trigger');if(kind==='role'){input.value=value;document.querySelectorAll('[data-biz-role]').forEach(x=>{const active=x.dataset.bizRole===value;x.classList.toggle('is-active',active);x.setAttribute('aria-selected',String(active));});trigger.querySelector('.select-text').textContent=value;trigger.querySelector('.select-text').classList.remove('select-text--placeholder');toggleBusiness(kind);}else{let selected=JSON.parse(input.value||'[]');selected=selected.includes(value)?selected.filter(x=>x!==value):[...selected,value];input.value=JSON.stringify(selected);$('#business-direction-chips').innerHTML=selected.length?selected.map(x=>`<span data-v-af111376 class="chip">${esc(x)}<span data-v-af111376 class="chip-close" role="button" tabindex="0" data-biz-remove="${esc(x)}" aria-label="移除${esc(x)}">×</span></span>`).join(''):'<span data-v-af111376 class="select-text select-text--placeholder" id="business-direction-text">请选择合作方向（可多选）</span>';trigger.setAttribute('aria-label','合作方向：'+(selected.join('、')||'未选择'));document.querySelectorAll('[data-biz-direction]').forEach(x=>{const chosen=selected.includes(x.dataset.bizDirection);x.classList.toggle('is-active',chosen);x.setAttribute('aria-selected',String(chosen));x.querySelector('.select-checkbox')?.classList.toggle('is-checked',chosen);});}trigger.closest('.form-select')?.classList.add('is-filled');updateBusiness();}
async function saveBusiness(event){event.preventDefault();if(loginBusy)return;const d=businessData();if(!d.name||!d.company||!/^1[3-9]\d{9}$/.test(d.contact)||!d.direction.length||!d.needs||!$('#business-agreement').checked){$('#business-error').textContent='请完善必填信息并同意隐私政策';return;}loginBusy=true;$('#business-submit').disabled=true;$('#business-submit').textContent='提交中...';await new Promise(r=>setTimeout(r,350));try{if(state.failNext){state.failNext=false;$('#simulateFailure').classList.remove('armed');throw new Error('提交失败，请重试；已保留填写内容。');}submitBusiness(d,state.region);loginBusy=false;closeModal();toast('合作意向已提交，我们将在 1 个工作日内与您联系');}catch(e){loginBusy=false;$('#business-error').textContent=e.message;$('#business-submit').textContent='重试提交';updateBusiness();}}
async function submitLogin(event){event.preventDefault();if(loginBusy)return;const phone=$('#phone').value.trim(),code=$('#code').value.trim();modalPhone=phone;const error=$('#loginError');if(!/^1[3-9]\d{9}$/.test(phone)){error.textContent='请输入正确的11位手机号';$('#phone').focus({preventScroll:true});return;}if(codePhone!==phone||Date.now()>codeExpires){error.textContent='请先获取该手机号的验证码，验证码有效期为5分钟';return;}if(code!=='123456'){error.textContent='验证码错误，请重新输入';$('#code').focus({preventScroll:true});return;}if(!$('#agreement').checked){error.textContent='请先阅读并同意用户协议和隐私政策';return;}error.textContent='';loginBusy=true;$('#submitLogin').disabled=true;$('#submitLogin').textContent='验证中...';await new Promise(r=>setTimeout(r,450));try{if(state.failNext){state.failNext=false;$('#simulateFailure').classList.remove('armed');throw new Error('请求失败，请稍后重试；当前未改变申请或登录状态。');}const row=requestAccess(phone,state.region,modalSource);if(row.status==='approved'){state.session={phone,region:state.region};localStorage.setItem(SESSION_KEY,JSON.stringify(state.session));loginBusy=false;closeModal();render();toast('登录成功');}else{loginBusy=false;error.innerHTML='暂无登录权限，<button type="button" id="loginBusiness" class="permission-contact">联系商务获取</button>。';$('#submitLogin').disabled=false;$('#submitLogin').textContent='登录/注册';}}catch(e){error.textContent=e.message;loginBusy=false;if($('#submitLogin')){$('#submitLogin').disabled=false;$('#submitLogin').textContent='登录/注册';}}}
function updateLogin(){const valid=/^1[3-9]\d{9}$/.test($('#phone').value.trim())&&/^\d{6}$/.test($('#code').value.trim())&&$('#agreement').checked;$('#submitLogin').classList.toggle('is-disabled',!valid);}
function sendCode(){const phone=$('#phone').value.trim();if(!/^1[3-9]\d{9}$/.test(phone))return;codePhone=phone;codeExpires=Date.now()+300000;$('#loginError').textContent='';let seconds=60;const button=$('#sendCode');button.disabled=true;button.textContent=`${seconds}s 后重发`;toast('验证码已模拟发送：123456（不会发送真实短信）');clearInterval(codeTimer);codeTimer=setInterval(()=>{seconds--;if(!button.isConnected){clearInterval(codeTimer);return;}button.textContent=seconds>0?`${seconds}s 后重发`:'获取验证码';if(seconds<=0){clearInterval(codeTimer);button.disabled=false;}},1000);}
function openTool(name){if(!currentUser()){openLogin(`${name}入口`);return;}modalShell(`<h2 id="modalTitle">${esc(name)}</h2><p>登录状态验证通过。正式环境将进入对应创作工具。</p><p>工具内部页面未涉及本次会议需求，本 Demo 不另行制作。</p><div class="modal-actions"><button data-close class="primary">返回当前页面</button></div>`,true);}
function showDetail(){toast('作品详情沿用现有官网，本次仅调整列表尾部登录入口。');}
document.addEventListener('click',event=>{const chip=event.target.closest('[data-biz-remove]');if(chip&&!loginBusy){pickBusiness('direction',chip.dataset.bizRemove);return;}const el=event.target.closest('button,a');if(!el)return;if(loginBusy){event.preventDefault();return;}
  if(el.dataset.bizToggle){toggleBusiness(el.dataset.bizToggle);}
  else if(el.dataset.bizRole){pickBusiness('role',el.dataset.bizRole);}
  else if(el.dataset.bizDirection){pickBusiness('direction',el.dataset.bizDirection);}
  else if(el.dataset.filterToggle){const panel=$('#filter-'+el.dataset.filterToggle);const open=panel.hidden;document.querySelectorAll('.filter-select__panel').forEach(x=>x.hidden=true);document.querySelectorAll('[data-filter-toggle]').forEach(x=>x.setAttribute('aria-expanded','false'));panel.hidden=!open;el.setAttribute('aria-expanded',String(open));}
  else if(el.dataset.filterName){state[el.dataset.filterName]=el.dataset.filterValue;const wrap=el.closest('.filter-select');wrap.querySelector('.filter-select__label').textContent=el.textContent;wrap.querySelector('.filter-select__panel').hidden=true;wrap.querySelector('button').setAttribute('aria-expanded','false');wrap.querySelectorAll('[data-filter-name]').forEach(x=>x.classList.toggle('is-active',x===el));renderLibraryResults();}
  else if(el.dataset.route){event.preventDefault();navigate(el.dataset.route);}
  else if(el.id==='switchEdition'){const region=state.region==='国内版'?'海外版':'国内版';state.session=null;localStorage.removeItem(SESSION_KEY);navigate('home',{region});syncPrd('overseas');toast(`已进入${region}，默认使用简体中文`);}
  else if(el.id==='navLogin'){if(!currentUser())openLogin();else modalShell(`<h2 id="modalTitle">已登录容量万相</h2><p>${esc(currentUser().phone)}</p><p>当前版本：${state.region}</p><div class="modal-actions"><button data-close>取消</button><button class="primary" id="logout">退出登录</button></div>`,true);}
  else if(el.id==='logout'){state.session=null;localStorage.removeItem(SESSION_KEY);closeModal();render();toast('已退出登录');}
  else if(el.hasAttribute('data-close'))closeModal();
  else if(el.id==='moreButton')openLogin(`${state.view==='novels'?'小说IP库':'剧本库'}查看更多`);
  else if(el.dataset.tool){el.dataset.tool==='商务合作'?business():openTool(el.dataset.tool);}
  else if(el.dataset.unrelated)toast(`${el.dataset.unrelated}未涉及本次需求，沿用现有官网。`);
  else if(el.id==='contactBusiness'||el.id==='loginBusiness'||el.id==='loginHelpBusiness')business();
  else if(el.id==='language')toast('当前为简体中文；海外版默认中文。其他语言设置沿用现有官网。');
  else if(el.id==='sendCode')sendCode();
  else if(el.id==='demoToolsButton'){const open=$('#demoTools').hidden;$('#demoTools').hidden=!open;el.setAttribute('aria-expanded',String(open));}
  else if(el.dataset.account)openLogin('顶部登录',el.dataset.account,true);
  else if(el.id==='simulateFailure'){state.failNext=!state.failNext;el.classList.toggle('armed',state.failNext);toast(state.failNext?'下一次有效登录请求将模拟失败':'已取消失败模拟');}
  else if(el.id==='resetDemo')modalShell('<h2 id="modalTitle">重置演示数据？</h2><p>仅重置本 Demo 的虚构申请与登录状态，不影响 QA 或任何真实数据。当前演示改动会被清除。</p><div class="modal-actions"><button data-close>取消</button><button class="primary" id="confirmReset">确认重置</button></div>',true);
  else if(el.id==='confirmReset'){resetDemo();state.session=null;state.failNext=false;$('#simulateFailure').classList.remove('armed');closeModal();render();toast('演示数据已重置');}
  else if(el.hasAttribute('data-reset-search')){state.query='';state.genre='';state.channel='';state.length='';render();}
  else if(el.dataset.novel)showDetail('novel',el.dataset.novel);
  else if(el.dataset.script)showDetail();
});
document.addEventListener('input',e=>{if(e.target.closest('#businessForm'))updateBusiness();if(e.target.closest('#loginForm'))updateLogin();if(e.target.id==='search'){state.query=e.target.value.trim();renderLibraryResults();}if(e.target.id==='phone'){if(!$('#sendCode').textContent.includes('s 后'))$('#sendCode').disabled=!/^1[3-9]\d{9}$/.test(e.target.value.trim());}});
document.addEventListener('change',e=>{if(e.target.closest('#loginForm'))updateLogin();if(e.target.closest('#businessForm'))updateBusiness();if(e.target.id?.startsWith('filter-')){state[e.target.id.slice(7)]=e.target.value;renderLibraryResults();}});
document.addEventListener('submit',e=>{if(e.target.id==='loginForm')submitLogin(e);if(e.target.id==='businessForm')saveBusiness(e);});
document.addEventListener('click',e=>{if(!e.target.closest('.filter-select')){document.querySelectorAll('.filter-select__panel').forEach(x=>x.hidden=true);document.querySelectorAll('[data-filter-toggle]').forEach(x=>x.setAttribute('aria-expanded','false'));}if($('#businessForm')&&!e.target.closest('.form-select,.select-dropdown')){document.querySelectorAll('#businessForm .select-dropdown').forEach(x=>x.hidden=true);document.querySelectorAll('[data-biz-toggle]').forEach(x=>{x.setAttribute('aria-expanded','false');x.classList.remove('is-open');});}});
$('#modalLayer').addEventListener('click',e=>{if(e.target===$('#modalLayer'))closeModal();});
document.addEventListener('keydown',e=>{if($('#modalLayer').hidden)return;const chip=e.target.closest('[data-biz-remove]');if(chip&&['Enter',' '].includes(e.key)&&!loginBusy){e.preventDefault();pickBusiness('direction',chip.dataset.bizRemove);return;}if(e.key==='Escape'){e.preventDefault();closeModal();}if(e.key==='Tab'){const els=[...$('#modalLayer').querySelectorAll('button:not(:disabled),a[href],input:not(:disabled),select,textarea')].filter(x=>x.offsetParent!==null);const first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus({preventScroll:true});}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus({preventScroll:true});}}});
subscribeUsers(()=>{renderNav();if(['novels','scripts'].includes(state.view)){$('#gateSlot').innerHTML=gate();renderLibraryResults();}});
window.addEventListener('storage',e=>{if(e.key===SESSION_KEY){try{state.session=JSON.parse(e.newValue||'null');}catch{state.session=null;}render();}});
window.addEventListener('popstate',()=>{params();render();});
params();render();
