import {getOutputSync} from './sync-model.js?v=20260916-publish1';
import {listDramas} from './dramas.js?v=20260916-publish1';
import {modeLabel,isFullNarration,outputCost} from './engine.js?v=20260916-publish1';

const marketOf=d=>d.config.source?.kind==='green'?d.config.source.market:'manual';
const currentConfirmed=o=>o.status==='ready'&&o.confirmed&&o.confirmedVersion===o.contentVersion;
export function taskMatches(b,status){
 if(status==='running')return b.status==='running';
 if(status==='review')return b.outputs.some(o=>['ready','issue'].includes(o.status)&&!currentConfirmed(o));
 if(status==='failed')return b.outputs.some(o=>o.status==='failed');
 return true;
}
export function renderLibrary(state,filters,h){
 const {heading,button,esc,tag,option,sourceLabel}=h;
 const all=listDramas(state),query=filters.query.trim().toLowerCase();
 const list=all.filter(d=>(filters.market==='all'||marketOf(d)===filters.market)&&(!query||(d.title+' '+d.id).toLowerCase().includes(query))&&(filters.status==='all'||filters.status==='running'&&d.runningCount>0||filters.status==='review'&&d.reviewCount>0||filters.status==='empty'&&!d.batches.length));
 return heading('剧目与剧情','',button('新增剧目','add-drama','primary'))+
 `<div class="library-overview"><span>共 <b>${all.length}</b> 部剧</span><span><b>${all.reduce((n,d)=>n+d.runningCount,0)}</b> 个任务制作中</span><span><b>${all.reduce((n,d)=>n+d.reviewCount,0)}</b> 条成片待检查</span><span><b>${all.reduce((n,d)=>n+d.syncedCount,0)}</b> 条当前版本已同步</span></div>
 <div class="library-filters"><input id="dramaSearch" aria-label="搜索剧目" placeholder="搜索剧名或合集 ID" value="${esc(filters.query)}"><select id="dramaMarket" aria-label="剧目来源">${[['all','全部来源'],['domestic','国内短剧'],['overseas','海外短剧'],['manual','手动片源']].map(([v,l])=>option(v,l,filters.market)).join('')}</select><select id="dramaStatus" aria-label="剧目工作状态">${[['all','全部状态'],['running','制作中'],['review','有待检查成片'],['empty','尚未制作']].map(([v,l])=>option(v,l,filters.status)).join('')}</select>${button('清空筛选','clear-drama-filters','text-btn')}</div>
 ${list.length?`<div class="table-wrap"><table class="drama-table"><thead><tr><th>剧目 / 来源</th><th>片源与分析</th><th>制作任务</th><th>成片与交付</th><th>操作</th></tr></thead><tbody>${list.map(d=>`<tr><td><div class="drama-name"><span class="drama-monogram ${marketOf(d)}">${marketOf(d)==='domestic'?'国':marketOf(d)==='overseas'?'海':'本'}</span><div><strong>${esc(d.title)}</strong><p>${sourceLabel(d.config)}</p><small>${esc(d.config.source.collectionId||d.config.source.assetId||'示例片源')}</small></div></div></td><td><b>${d.availableCount}</b> / ${d.totalEpisodes} 集可用<p>已分析 ${d.analyzedCount} 集 · 原片 V${d.config.source.fileVersion||1}</p>${d.availableCount<d.totalEpisodes?tag('部分剧集待准备','orange'):''}</td><td><b>${d.batches.length}</b> 个批次<p>${d.runningCount?'制作中 '+d.runningCount+' 个':d.batches.length?'已完成 '+d.batches.length+' 个':'还没有制作任务'}</p>${d.failedCount?tag(d.failedCount+' 个任务需补生成','orange'):''}</td><td><b>${d.generatedCount}</b> 条已生成<p>${d.reviewCount?'<span class="needs-attention">'+d.reviewCount+' 条待检查</span>':'待检查 0 条'} · 已确认 ${d.confirmedCount}</p><small>当前版本已同步 ${d.syncedCount} 条</small></td><td><div class="row-actions">${button('查看剧目','open-drama','text-btn',`data-id="${esc(d.id)}"`)}${button('继续制作','make-drama','secondary',`data-id="${esc(d.id)}"`)}</div></td></tr>`).join('')}</tbody></table></div>`:`<div class="empty"><h2>没有符合条件的剧目</h2><p>可以清空筛选，或从绿台合集新增一部剧。</p>${button('清空筛选','clear-drama-filters','secondary')}${button('新增剧目','add-drama','primary')}</div>`}
 <div class="table-footer"><span></span><span>显示 ${list.length} / ${all.length} 部</span></div>`;
}
export function renderTaskTable(batches,h){
 const {button,esc,tag,sourceLabel}=h;
 if(!batches.length)return `<div class="empty"><h2>暂无符合条件的制作任务</h2><p>选择制作方式与集数，即可开始新的一批。</p>${button('制作素材','create','primary')}</div>`;
 return `<div class="table-wrap"><table class="library-task-table"><thead><tr><th>剧目 / 制作批次</th><th>制作方式</th><th>生成 / 已确认</th><th>每条可用素材消费</th><th>状态</th><th>操作</th></tr></thead><tbody>${batches.map(b=>{const cost=outputCost(b),failed=b.outputs.filter(o=>o.status==='failed').length,review=b.outputs.filter(o=>['ready','issue'].includes(o.status)&&!currentConfirmed(o)).length;return `<tr><td><strong>${esc(b.sourceTitle)}</strong><p>${esc(b.id)}</p><small>${sourceLabel(b.config)} · ${new Date(b.created).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}</small></td><td>${modeLabel(b.config)}<p>第 ${b.config.start}–${b.config.end} 集 · ${isFullNarration(b.config)?'解说 '+(b.config.narrationSpeed||1)+'×':'原片 '+b.config.speed+'×'+(b.config.mode==='narrated'?' · 解说 '+(b.config.narrationSpeed||1)+'×':'')}</p></td><td>${b.outputs.filter(o=>['ready','issue'].includes(o.status)).length} / ${cost.accepted} 条<p>${review?'待检查 '+review+' 条':'当前无待检查成片'}</p></td><td>${cost.per===null?'待确认可用':'¥'+cost.per.toFixed(2)}</td><td>${tag(b.status==='running'?'制作中':failed?'部分未完成':'已完成',b.status==='running'||failed?'orange':'green')}${failed?'<p>'+failed+' 条需补生成</p>':''}</td><td><div class="row-actions">${button('查看成片','open-task','text-btn',`data-id="${esc(b.id)}"`)}${button('再做一批','repeat-batch','text-btn',`data-id="${esc(b.id)}"`)}</div></td></tr>`;}).join('')}</tbody></table></div>`;
}
export function renderDrama(d,tab,body,h){
 const {heading,button,esc,tag,sourceLabel}=h;
 return `<div class="drama-back">${button('‹ 返回剧目列表','assets','text-btn')}</div>`+heading(esc(d.title),`${sourceLabel(d.config)} · ${d.availableCount} / ${d.totalEpisodes} 集可用`,button('继续制作','make-drama','primary',`data-id="${esc(d.id)}"`))+
 `<div class="library-overview"><span>已分析 <b>${d.analyzedCount}</b> 集</span><span>制作任务 <b>${d.batches.length}</b> 个</span><span>待检查 <b>${d.reviewCount}</b> 条</span><span>已确认 <b>${d.confirmedCount}</b> 条</span><span>已同步 <b>${d.syncedCount}</b> 条</span></div>
 <div class="drama-tabs" role="tablist" aria-label="剧目详情">${[['plot','片源与剧情'],['tasks','制作任务 · '+d.batches.length],['outputs','成片与交付 · '+d.generatedCount]].map(([v,l])=>button(l,'drama-tab',tab===v?'active':'',`data-value="${v}" role="tab" aria-selected="${tab===v}"`)).join('')}</div><div role="tabpanel">${body}</div>`;
}
export function renderDramaOutputs(d,filter,h,state){
 const {button,esc,tag,option,fmt}=h;
 const rows=d.batches.flatMap(b=>b.outputs.map(o=>({b,o}))).filter(({b,o})=>filter==='all'||filter==='review'&&['ready','issue'].includes(o.status)&&!currentConfirmed(o)||filter==='confirmed'&&currentConfirmed(o)||filter==='synced'&&getOutputSync(b.id,o,state.syncJobs)?.status==='success');
 return `<div class="toolbar"><h2>该剧全部成片</h2><select id="dramaOutputFilter" aria-label="成片状态">${[['all','全部成片'],['review','待检查'],['confirmed','已确认可用'],['synced','当前版本已同步']].map(([v,l])=>option(v,l,filter)).join('')}</select></div>${rows.length?`<div class="table-wrap"><table><thead><tr><th>成片 / 批次</th><th>制作方式</th><th>时长 / 版本</th><th>检查状态</th><th>素材交付</th><th>操作</th></tr></thead><tbody>${rows.map(({b,o})=>{const item=getOutputSync(b.id,o,state.syncJobs);return `<tr><td><strong>${esc(o.title)}</strong><p>${esc(b.id)}</p></td><td>${modeLabel(b.config)}</td><td>${fmt(o.duration)}<p>V${o.contentVersion}</p></td><td>${tag(o.status==='pending'?'制作中':o.status==='failed'?'生成失败':o.status==='issue'?'有问题待修复':currentConfirmed(o)?'已确认可用':'待检查',currentConfirmed(o)?'green':'orange')}</td><td>${tag(item?.status==='success'?'已同步':item?.status==='unknown'?'待核实':item?.status==='failed'?'同步失败':['pending','processing'].includes(item?.status)?'同步中':'未同步',item?.status==='success'?'green':'')}<p>${item?.item?.materialId?esc(item.item.materialId):''}</p></td><td>${['ready','issue'].includes(o.status)?button('检查成片','review-drama-output','text-btn',`data-batch="${esc(b.id)}" data-id="${esc(o.id)}"`):button('查看任务','open-task','text-btn',`data-id="${esc(b.id)}"`)}</td></tr>`;}).join('')}</tbody></table></div>`:`<div class="empty"><h2>暂无符合条件的成片</h2><p>制作完成后，可在这里集中检查并查看素材交付状态。</p>${button('查看制作任务','drama-tab','secondary','data-value="tasks"')}</div>`}`;
}
